# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/hassio-addons/base:20.0.1"
  amd64: "ghcr.io/hassio-addons/base:20.0.1"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Pangolin CLI Add-On"
  org.opencontainers.image.description: "Addon will run the Pangolin CLI inside Home Assistant OS."
  org.opencontainers.image.source: "https://github.com/OnyxChills/home-assistant-pangolin-cli-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"
  io.hass.version: "VERSION"
  io.hass.type: "addon"
  io.hass.arch: "aarch64|amd64"
args:
  TEMPIO_VERSION: "2021.09.0"
